class EnvProperty:

    ENV_FILE = 'ISERV_ENV_FILE'
    SECRET_KEY = 'ISERV_SECRET_KEY'
    DEBUG_MODE = 'ISERV_DEBUG_MODE'
    ALLOWED_HOSTS = 'ISERV_ALLOWED_HOSTS'
    ALLOWED_CORHEADERS = 'ISERV_CORHEADERS_HOSTS'
    DATABASE_URL_DEFAULT = 'ISERV_DATABASE_URL'
    DATABASE_URL_SECONDARY = 'SECONDARY_DATABASE_URL'
    COOKIE_DOMAIN = 'ISERV_COOKIE_DOMAIN'
    COOKIE_NAME = 'ISERV_COOKIE_NAME'
    
    EMAIL_USE_TLS = 'ISERV_EMAIL_USE_TLS'
    EMAIL_HOST = 'ISERV_EMAIL_HOST'
    EMAIL_HOST_USER = 'ISERV_EMAIL_HOST_USER'
    EMAIL_HOST_PASSWORD = 'ISERV_EMAIL_HOST_PASSWORD'
    EMAIL_PORT = 'ISERV_EMAIL_PORT'
    
    URL_ADMINISTRA='ISERV_URL_ADMINISTRA'
    URL_REPORTS='ISERV_URL_REPORTS'
    URL_ADMINISTRA_TEMPLATE='ISERV_URL_ADMINISTRA_TEMPLATE'
    URL_API_SIE='ISERV_API_SIE'
    URL_API_INTERNA='ISERV_API_INTERNA'
    URL_API_SISMA='ISERV_API_SISMA' 
       
    LOG_LVL_ROOT = 'ISERV_LOG_LVL_ROOT'
    LOG_LVL_DJANGO = 'ISERV_LOG_LVL_DJANGO'
    LOG_LVL_DJANGO_SERVER = 'ISERV_LOG_LVL_DJANGO_SERVER'
