class EnvProperty:
    
    ENV_FILE = 'ISERV_ENV_FILE'
    SECRET_KEY = 'ISERV_SECRET_KEY'
    DEBUG_MODE = 'ISERV_DEBUG_MODE'
    ALLOWED_HOSTS = 'ISERV_ALLOWED_HOSTS'
    ALLOWED_CORHEADERS = 'ISERV_CORHEADERS_HOSTS'
    DATABASE_URL_DEFAULT = 'ISERV_DATABASE_URL'
    DATABASE_URL_SECONDARY = 'SECONDARY_DATABASE_URL'
    COOKIE_DOMAIN = 'ISERV_COOKIE_DOMAIN'
    COOKIE_NAME = 'ISERV_COOKIE_NAME'
       
    LOG_LVL_ROOT = 'ISERV_LOG_LVL_ROOT'
    LOG_LVL_DJANGO = 'ISERV_LOG_LVL_DJANGO'
    LOG_LVL_DJANGO_SERVER = 'ISERV_LOG_LVL_DJANGO_SERVER'
