# Generated by Django 4.1 on 2022-08-25 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                (
                    "nomeCompleto",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[(1, "Medico"), (2, "Enfermeira")],
                        verbose_name="Tipo pessoa",
                    ),
                ),
                (
                    "sala",
                    models.CharField(max_length=120, unique=True, verbose_name="Sala"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
            },
        ),
        migrations.CreateModel(
            name="PrioridadeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
            ],
            options={
                "verbose_name": "prioridade",
                "verbose_name_plural": "prioridades",
            },
        ),
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("senha", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Espera"), (2, "Atendida")], verbose_name="Status"
                    ),
                ),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[(1, "Convencional"), (2, "Preferencial")],
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "horaEmitida",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
                (
                    "horaChamada",
                    models.DateTimeField(null=True, verbose_name="Data e Hora"),
                ),
            ],
            options={
                "verbose_name": "Senha",
                "verbose_name_plural": "Senhas",
            },
        ),
        migrations.CreateModel(
            name="Triagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomePaciente", models.CharField(max_length=220)),
                (
                    "estado",
                    models.IntegerField(
                        choices=[(1, "espera"), (2, "atendido")],
                        verbose_name="Estado da Triagem",
                    ),
                ),
                ("senha", models.CharField(max_length=20, unique=True)),
                (
                    "sexo",
                    models.IntegerField(
                        choices=[(1, "Masculino"), (2, "Feminino")],
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "queixaPrincipal",
                    models.TextField(blank=True, null=True, verbose_name="Queixa"),
                ),
                (
                    "historicoBreve",
                    models.TextField(blank=True, null=True, verbose_name="Historico"),
                ),
                (
                    "observacaoObjetiva",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações do Enfermeiro"
                    ),
                ),
                (
                    "dor",
                    models.IntegerField(
                        choices=[(1, "Sim"), (2, "Não")], null=True, verbose_name="Dor"
                    ),
                ),
                ("frequenciaCardiaca", models.IntegerField()),
                ("frequenciaRespiratoria", models.IntegerField()),
                ("pressaoArterial", models.IntegerField()),
                ("temperatura", models.FloatField()),
                (
                    "classificacao",
                    models.IntegerField(
                        choices=[
                            (1, "Emergência"),
                            (2, "Muito Urgente"),
                            (3, "Urgente"),
                            (4, "Pouco Urgente"),
                            (5, "Não Urgente"),
                        ],
                        null=True,
                        verbose_name="Classificacao",
                    ),
                ),
                (
                    "atendente",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atendimento.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Triagem",
                "verbose_name_plural": "Triagems",
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnostico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnostico médico"
                    ),
                ),
                (
                    "medicoAtendente",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atendimento.pessoa",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atendimento.triagem",
                    ),
                ),
            ],
        ),
    ]
